# Change these first
owner: VertaStack # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Skarleto
    url: https://skarleto.com
    method: GET
    maxResponseTime: 5000
    id: skarleto
    type: globalping
    location: sofia
  - name: Starpi
    url: https://admin.fortuslab.com/
    method: GET
    maxResponseTime: 15000
    id: strapi
    type: globalping
    location: sofia
  - name: VertaStack
    url: https://vertastack.com
    method: GET
    maxResponseTime: 15000
    id: vertastack
    type: globalping
    location: sofia
  - name: FortusLab
    url: https://fortuslab.com
    method: GET
    maxResponseTime: 15000
    id: fortuslab
    type: globalping
    location: sofia
  - name: Diverso
    url: https://diversovastgoedonderhoud.nl
    method: GET
    maxResponseTime: 15000
    id: diverso
    type: globalping
    location: sofia
  - name: Skarleto
    url: https://nikolaydimitrov.dev
    method: GET
    maxResponseTime: 5000
    id: nikolaydimitrov
    type: globalping
    location: sofia
assignees: 
  - ngdimitrov
  - AntonMingov
  - lexa497
status-website:
  baseUrl: /upptime # where "repo" is your repository name
  name: Uptime
  introTitle: "**VertaStack Uptime** monitoring status page"
  introMessage: "This site monitors the availability of **VertaStack** services in real time via GitHub Actions and Upptime."
